### ISSUE TITLE
check that db initialization was done properly

### ISSUE THREAD

**Issue by gracenoah** [satoshipay/docker-stellar-horizon#10] opened 2019-02-06 05:41 UTC
I'm running into an issue in CI where if horizon starts up before everything else and it hasn't performed db initialization, it can get into a broken state where it's running but never initialized the database. I don't know if this is a horizon bug, a docker image startup script bug or both, but I think this issue can be worked around in the startup script by checking more specifically that db initialization was done.

Logs:
```
stellar-horizon_1     | 2019-02-05T17:39:52.920368516Z Initializing Horizon database...
stellar-horizon_1     | 2019-02-05T17:39:53.004165677Z Horizon database initialization failed (possibly because it has been done before)
stellar-horizon_1     | 2019-02-05T17:39:53.004197994Z time="2019-02-05T17:39:52.998Z" level=error msg="connect failed: pq: the database system is starting up" pid=7 
stellar-horizon_1     | 2019-02-05T17:39:53.581502682Z time="2019-02-05T17:39:53.581Z" level=warning msg="could not load stellar-core info: http request errored: Get http://<redacted>:11626/info: dial tcp 172.18.0.2:11626: connect: connection refused" pid=1 
stellar-horizon_1     | 2019-02-05T17:39:53.590863575Z time="2019-02-05T17:39:53.590Z" level=info msg="Starting horizon on :8000 (ingest: true)" pid=1 
stellar-horizon_1     | 2019-02-05T17:39:54.005158450Z time="2019-02-05T17:39:54.005Z" level=error msg="failed to load operation fee stats state" err="get failed: pq: relation "history_ledgers" does not exist" pid=1 stack="[main.go:43 session.go:106 main.go:322 app.go:206 app.go:313 asm_amd64.s:1333]" 
stellar-horizon_1     | 2019-02-05T17:39:54.006246193Z time="2019-02-05T17:39:54.006Z" level=error msg="failed to load ledger state" err="get failed: pq: relation "history_ledgers" does not exist" pid=1 stack="[main.go:43 session.go:106 main.go:316 app.go:176 app.go:312 asm_amd64.s:1333]" 
```

**Comment by andrenarchy** [comment] 2019-02-18 16:14
Thanks for reporting this! I'll relay this to the Horizon devs, I think Horizon should exit with a non-zero exit code if it can't connect to the database.

**Comment by andrenarchy** [comment] 2019-02-18 16:35
I opened https://github.com/stellar/go/issues/898 so I'm closing this one. Please reopen if the issue is actually in the Docker image's entrypoint!

**Closed as completed by andrenarchy** 2019-02-18 16:35 UTC
